### PR TITLE
isolate bad workers when dispatch traffic 

### PR DESCRIPTION
**Pull request by anderswei**
This PR fixed several problems for shackle:

- if a worker is down, then shackle shouldn't route any requests to that worker.
- if too many workers are down, then call back to marina pool to stop routing any traffics to this worker pool.
- if workers recovered, then callback to marina to resume requests to this pool.

### CODE REVIEW

**Comment by lpgauth** [comment]
Hi, thanks for the PR. I'll try to review it this week.

**Comment by lpgauth** [comment]
FYI, my plan to bypass workers was to use negative values for the backlog but I never got around to it.

https://github.com/lpgauth/shackle/issues/42

**Comment by lpgauth** [comment]
Hi, I've implemented a status module to keep track of active servers and added retries. I'm just missing the callback now, I'm debating what the best strategy to implement it is.

See: https://github.com/lpgauth/shackle/pull/100

**Comment by lpgauth** [comment]
I'm not a big fan of the current heuristic used for checking the pool health (up / down). Have you used it in prod? Does it work well?

**Comment by lpgauth** [comment]
Superseded by: https://github.com/lpgauth/shackle/pull/100

**Comment by anderswei** [comment]
@lpgauth if you are not a big fan, then give comment and I will try to update the code, instead of just creating a new PR on your own and do what this PR supposed to do. I don't think it is the right way of making things work.

**Comment by lpgauth** [comment]
I did comment 18 days ago and you never replied. 

If you're unhappy, just use your branch. This is the beauty of Git and OOS.

**Pull request closed without merging**
