### PR TITLE
monitor server process during call

### PR DESCRIPTION
**Pull request by tsloughter**
Possible fix for #61 

Threw this together tonight to get a discussion going. I haven't thought about potential unintended consequences or better code sharing between call and cast like there was before, but will tomorrow.

### CODE REVIEW

**Comment by lpgauth** [comment]
Hi @tsloughter,
I've been thinking about this and I was kind of leaning more towards wrapping any client calls inside a `try/catch`. My only concern is performance so I'll have to run some benchmark before moving forward with that.

LP

**Comment by tsloughter** [comment]
@lpgauth is that because there is more to the issue than just the client side timeout? Like it needs to clean up the queue inside shackle?

**Comment by lpgauth** [comment]
Yeah, there might be some side effects that are not properly cleaned up if you crash and recover.

**Comment by lpgauth** [comment]
FYI, started https://github.com/lpgauth/shackle/pull/87 to resolve https://github.com/lpgauth/shackle/issues/61.

**Comment by lpgauth** [comment]
Closing this PR, feature implemented in https://github.com/lpgauth/shackle/pull/87.

**Pull request closed without merging**
