### PR TITLE
Add Aerospike Client, 'aspike-node', to Client's list

### PR DESCRIPTION
**Pull request by vsavkov**
'shackle' is used by Erlang Aerospike client, aspike-node'.

### CODE REVIEW

**Comment by lpgauth** [comment]
Cool. You guys are moving away from scylla?

**Comment by vsavkov** [comment]
Considering, not set in stone yet. Sorry, for the delayed response.

**Comment by lpgauth** [comment]
@vsavkov are there any specific reasons you're moving away from Scylla? Cost?

**Comment by vsavkov** [comment]
@lpgauth I'm not on the level to make decisions about the infrastructure, so, don't know the rationale behind the initiative to use Aerospike instead of Scylla.

**Pull request merged**
