### PR TITLE
Integrate with :telemetry

### PR DESCRIPTION
**Pull request by rkallos**
`:telemetry` seems to be picking up steam as the way forward for libraries to emit telemetry for applications. This largely replaces your use of `?METRICS` calls with matching calls to the new `shackle_telemetry` module.

Also, a bunch of links in the docs got updated when I regenerated them. It might be worth looking into generating them with [`rebar3_ex_doc`](https://hexdocs.pm/rebar3_ex_doc/readme.html) so they turn into pretty docs on hexdocs.pm.

### CODE REVIEW

**Comment by lpgauth** [comment]
Did I quick review and it looks good. Once thing I noticed is that the dep wasn't added to the 'rebar.config.script' file which TBH I don't remember what it was used for...

What else could I do to make shackle more elixir friendly? mix config file and a shackle.ex file to expose the main APIs?

**Comment by lpgauth** [comment]
Oh, I think the `rebar.config.script` was for rebar2 compatibility. I think I can clean this up now.

**Comment by rkallos** [comment]
> What else could I do to make shackle more elixir friendly?

It's an interesting question! I haven't given it much thought because I haven't really been using shackle directly; I've been using buoy. I suspect I'd have a much clearer picture if I write a shackle client in Elixir.

I think one big improvement might be having docs generated and uploaded to hexdocs, using an approach similar to [`:telemetry`](https://hexdocs.pm/telemetry/readme.html). The repo has a basic `mix.exs` file, and I suspect that, when publishing to hex, `mix docs` is the task that builds the documentation that winds up on Hexdocs.

**Comment by rkallos** [comment]
I got `rebar3_ex_doc` working. However, there's a bit of ugliness. There's a section for each module where defined types are listed. Since a bunch of modules have `-include("shackle_internal.hrl").`, there are a bunch of duplicate definitions for those types. It also appears as though jumping to source for those type definitions doesn't work either.

I think it would be pretty straightforward to move type definitions into the modules where they're used the most.

**Comment by rkallos** [comment]
I cleaned up a lot of the duplicated types in [this branch](https://github.com/rkallos/shackle/compare/telemetry...rkallos:shackle:remove-type-duplication) (based on top of this PR branch). The resulting generated documentation is much cleaner, and linking back to definitions and whatnot is much nicer.

**Review by lpgauth — APPROVED** [review]
LGTM.

**Comment by x0id** [comment]
With all respect to `telemetry` devs, I think this PR is a step back.

1. The original hooks are based on the foil library which is faster than ets lookups (used internally by telemetry to get a list of handlers).
2. The `telemetry` calls, if needed, might be implemented via original hooks with no need to introduce an extra dependency on the library which not everybody is interested in.

**Comment by lpgauth** [comment]
@x0id Hey, I'll talk @rkallos and discuss what we should do. I agree that this implementation is a bit slower because of the ETS calls. 

Moving forward I see two options:
1) Switch back to hooks, but also ship a telemetry module with Shackle so it can be easily enabled.
2) Fork/open a PR to have `telemetry` use `foil`.

**Pull request merged**
